### ISSUE TITLE
System does not login

### ISSUE THREAD

**Issue by leocampbel** [bkbilly/AlarmPI#26]
**Describe the problem**
I thank everyone who makes this system, I installed alarmpi without errors, I put a difficult password, but both in the login of the browser itself on localhost and of another machine with the raspibery ip I cannot log in, simply nothing happens, and not even a message from error happens, I reinstalled the system and put a simple password and still does not login

**OS Version**
Raspbery pi OS 32bits

**AlarmPI version** 
4.7

**Error Logs**
no logs
```txt

```

```json

```

**Comment by detxm80** [comment]
same problem here, and https doesn't work

**Comment by bkbilly** [comment]
The default credentials are:
user: test1
pass: secret

In case you want to change them or find the current ones you can find them under the folder `/opt/AlarmPI/config/server.json`.

You can find what this file looks like here:
https://github.com/bkbilly/AlarmPI/blob/master/config/server_template.json

As for the HTTPs, @detxm80 you will have to tell me more information about your problem and I would recommend doing this in a new issue.

If you are able to login, let me know to close this issue because I can't find anything wrong with the installation process of AlarmPI.

**Comment by detxm80** [comment]
> The default credentials are: user: test1 pass: secret
> 
> In case you want to change them or find the current ones you can find them under the folder `/opt/AlarmPI/config/server.json`.
> 
> You can find what this file looks like here: https://github.com/bkbilly/AlarmPI/blob/master/config/server_template.json
> 
> As for the HTTPs, @detxm80 you will have to tell me more information about your problem and I would recommend doing this in a new issue.
> 
> If you are able to login, let me know to close this issue because I can't find anything wrong with the installation process of AlarmPI.

ok i've modified user and than it's all ok, but there is a bug in your bash install that will not create a user but an a test1 user only.

https i understand that i create certificate manually, solved

sorry for my english, compliments for you project and for your support.....now i try it :)

**Comment by bkbilly** [comment]
Feel free to write any problem you have here, but if you create a new issue, there are instructions on some helpful things that might help me identify the issue easier.

I will take a look at the script to see how it can be fixed.

**Comment by leocampbel** [comment]
Hello, thank you for the feedback, I managed to log in, the system to register the user in the installation does not really work, but the rest is working. thank you so much for the program!!!!
